<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Tbbc__MoneyBundle__Entity__DoctrineStorageRatio__CLASSMETADATA__' => 0,
'Tbbc__MoneyBundle__Entity__RatioHistory__CLASSMETADATA__' => 1,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Tbbc\\MoneyBundle\\Entity\\DoctrineStorageRatio',
                ],
                'namespace' => [
                    'Tbbc\\MoneyBundle\\Entity',
                ],
                'rootEntityName' => [
                    'Tbbc\\MoneyBundle\\Entity\\DoctrineStorageRatio',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'currencyCode' => [
                            'fieldName' => 'currencyCode',
                            'type' => 'string',
                            'columnName' => 'currency_code',
                            'length' => 3,
                            'unique' => true,
                            'nullable' => false,
                        ],
                        'ratio' => [
                            'fieldName' => 'ratio',
                            'type' => 'float',
                            'columnName' => 'ratio',
                            'length' => 255,
                            'nullable' => false,
                        ],
                        'id' => [
                            'id' => true,
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'columnName' => 'id',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'currency_code' => 'currencyCode',
                        'ratio' => 'ratio',
                        'id' => 'id',
                    ],
                ],
                'columnNames' => [
                    [
                        'currencyCode' => 'currency_code',
                        'ratio' => 'ratio',
                        'id' => 'id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'tbbc_money_doctrine_storage_ratios',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Tbbc\\MoneyBundle\\Entity\\RatioHistory',
                ],
                'namespace' => [
                    'Tbbc\\MoneyBundle\\Entity',
                ],
                'rootEntityName' => [
                    'Tbbc\\MoneyBundle\\Entity\\RatioHistory',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'currencyCode' => [
                            'fieldName' => 'currencyCode',
                            'type' => 'string',
                            'columnName' => 'currency_code',
                            'length' => 3,
                            'nullable' => false,
                        ],
                        'referenceCurrencyCode' => [
                            'fieldName' => 'referenceCurrencyCode',
                            'type' => 'string',
                            'columnName' => 'reference_currency_code',
                            'length' => 3,
                            'nullable' => false,
                        ],
                        'ratio' => [
                            'fieldName' => 'ratio',
                            'type' => 'float',
                            'columnName' => 'ratio',
                            'length' => 255,
                            'nullable' => false,
                        ],
                        'savedAt' => [
                            'fieldName' => 'savedAt',
                            'type' => 'datetime',
                            'columnName' => 'saved_at',
                            'nullable' => false,
                        ],
                        'id' => [
                            'id' => true,
                            'fieldName' => 'id',
                            'type' => 'integer',
                            'columnName' => 'id',
                        ],
                    ],
                ],
                'fieldNames' => [
                    [
                        'currency_code' => 'currencyCode',
                        'reference_currency_code' => 'referenceCurrencyCode',
                        'ratio' => 'ratio',
                        'saved_at' => 'savedAt',
                        'id' => 'id',
                    ],
                ],
                'columnNames' => [
                    [
                        'currencyCode' => 'currency_code',
                        'referenceCurrencyCode' => 'reference_currency_code',
                        'ratio' => 'ratio',
                        'savedAt' => 'saved_at',
                        'id' => 'id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'tbbc_money_ratio_history',
                    ],
                ],
                'idGenerator' => [
                    $o[1],
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
