FROM php:8.1
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN apt-get update && apt-get install -y git curl nano zip libicu-dev \
    && docker-php-ext-install intl bcmath
WORKDIR /docker

CMD ["bash"]
