<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_Doctrine_Orm_Default_Query_CompatibilityLayerService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the private 'cache.doctrine.orm.default.query.compatibility_layer' shared service.
     *
     * @return \Doctrine\Common\Cache\CacheProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['cache.doctrine.orm.default.query.compatibility_layer'] = \Doctrine\Common\Cache\Psr6\DoctrineProvider::wrap(($container->privates['cache.doctrine.orm.default.query'] ?? ($container->privates['cache.doctrine.orm.default.query'] = new \Symfony\Component\Cache\Adapter\ArrayAdapter())));
    }
}
