<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestRatioProviderService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the private 'test_ratio_provider' shared service.
     *
     * @return \Tbbc\MoneyBundle\Pair\RatioProvider\StaticRatioProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['test_ratio_provider'] = $instance = new \Tbbc\MoneyBundle\Pair\RatioProvider\StaticRatioProvider();

        $instance->setRatio('EUR', 'USD', 1.089);
        $instance->setRatio('EUR', 'CAD', 1.452);

        return $instance;
    }
}
