<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_Pair_CsvStorageService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.pair.csv_storage' shared service.
     *
     * @return \Tbbc\MoneyBundle\Pair\Storage\CsvStorage
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.pair.csv_storage'] = new \Tbbc\MoneyBundle\Pair\Storage\CsvStorage((\dirname(__DIR__, 4).'/../data/tbbc_money/ratio_file_name.csv'), 'EUR');
    }
}
