<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_RatioProvider_GoogleService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.ratio_provider.google' shared service.
     *
     * @return \Tbbc\MoneyBundle\Pair\RatioProvider\GoogleRatioProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.ratio_provider.google'] = new \Tbbc\MoneyBundle\Pair\RatioProvider\GoogleRatioProvider();
    }
}
