<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_PairHistoryManagerService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.pair_history_manager' shared service.
     *
     * @return \Tbbc\MoneyBundle\PairHistory\PairHistoryManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.pair_history_manager'] = new \Tbbc\MoneyBundle\PairHistory\PairHistoryManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), 'EUR');
    }
}
