<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_FormType_SimpleMoneyService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the private 'tbbc_money.form_type.simple_money' shared service.
     *
     * @return \Tbbc\MoneyBundle\Form\Type\SimpleMoneyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['tbbc_money.form_type.simple_money'] = new \Tbbc\MoneyBundle\Form\Type\SimpleMoneyType(3, $container->parameters['tbbc_money.currencies'], 'EUR');
    }
}
