<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_Twig_CurrencyService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.twig.currency' shared service.
     *
     * @return \Tbbc\MoneyBundle\Twig\Extension\CurrencyExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.twig.currency'] = new \Tbbc\MoneyBundle\Twig\Extension\CurrencyExtension(($container->services['tbbc_money.formatter.money_formatter'] ?? ($container->services['tbbc_money.formatter.money_formatter'] = new \Tbbc\MoneyBundle\Formatter\MoneyFormatter(3))));
    }
}
