<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_PairManagerService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.pair_manager' shared service.
     *
     * @return \Tbbc\MoneyBundle\Pair\PairManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['tbbc_money.pair_manager'] = $instance = new \Tbbc\MoneyBundle\Pair\PairManager(($container->services['tbbc_money.pair.csv_storage'] ?? ($container->services['tbbc_money.pair.csv_storage'] = new \Tbbc\MoneyBundle\Pair\Storage\CsvStorage((\dirname(__DIR__, 4).'/../data/tbbc_money/ratio_file_name.csv'), 'EUR'))), $container->parameters['tbbc_money.currencies'], 'EUR', ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        $instance->setRatioProvider(($container->privates['test_ratio_provider'] ?? $container->load('getTestRatioProviderService')));

        return $instance;
    }
}
