<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_Formatter_MoneyFormatterService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.formatter.money_formatter' shared service.
     *
     * @return \Tbbc\MoneyBundle\Formatter\MoneyFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.formatter.money_formatter'] = new \Tbbc\MoneyBundle\Formatter\MoneyFormatter(3);
    }
}
