<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_Command_RatioSaveService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the private 'tbbc_money.command.ratio_save' shared service.
     *
     * @return \Tbbc\MoneyBundle\Command\RatioSaveCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['tbbc_money.command.ratio_save'] = $instance = new \Tbbc\MoneyBundle\Command\RatioSaveCommand(($container->services['tbbc_money.pair_manager'] ?? $container->load('getTbbcMoney_PairManagerService')));

        $instance->setName('tbbc:money:ratio-save');

        return $instance;
    }
}
