<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_MoneyManagerService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.money_manager' shared service.
     *
     * @return \Tbbc\MoneyBundle\Money\MoneyManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.money_manager'] = new \Tbbc\MoneyBundle\Money\MoneyManager('EUR', 3);
    }
}
