<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_Twig_MoneyService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the public 'tbbc_money.twig.money' shared service.
     *
     * @return \Tbbc\MoneyBundle\Twig\Extension\MoneyExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['tbbc_money.twig.money'] = new \Tbbc\MoneyBundle\Twig\Extension\MoneyExtension(($container->services['tbbc_money.formatter.money_formatter'] ?? ($container->services['tbbc_money.formatter.money_formatter'] = new \Tbbc\MoneyBundle\Formatter\MoneyFormatter(3))), ($container->services['tbbc_money.pair_manager'] ?? $container->load('getTbbcMoney_PairManagerService')));
    }
}
