<?php

namespace Container3VVPK3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbbcMoney_FormType_MoneyService extends Tbbc_MoneyBundle_Tests_AppKernelTestContainer
{
    /*
     * Gets the private 'tbbc_money.form_type.money' shared service.
     *
     * @return \Tbbc\MoneyBundle\Form\Type\MoneyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['tbbc_money.form_type.money'] = new \Tbbc\MoneyBundle\Form\Type\MoneyType(3);
    }
}
