<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3VVPK3j\Tbbc_MoneyBundle_Tests_AppKernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3VVPK3j/Tbbc_MoneyBundle_Tests_AppKernelTestContainer.php') {
    touch(__DIR__.'/Container3VVPK3j.legacy');

    return;
}

if (!\class_exists(Tbbc_MoneyBundle_Tests_AppKernelTestContainer::class, false)) {
    \class_alias(\Container3VVPK3j\Tbbc_MoneyBundle_Tests_AppKernelTestContainer::class, Tbbc_MoneyBundle_Tests_AppKernelTestContainer::class, false);
}

return new \Container3VVPK3j\Tbbc_MoneyBundle_Tests_AppKernelTestContainer([
    'container.build_hash' => '3VVPK3j',
    'container.build_id' => '4634f5b3',
    'container.build_time' => 1639218670,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3VVPK3j');
